#! /usr/bin/env bash

# Copyright (C) 2025 Mattéo Rossillol‑‑Laruelle <beatussum@protonmail.com>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <https://www.gnu.org/licenses/>.


set -o pipefail

readonly NAME="${BASH_SOURCE[0]##*/}"

########
# CORE #
########

die()
{
	local msg="$*"

	printf "fatal error: %s\n" "${msg}"
	exit 1
}

###########
# HELPERS #
###########

get_files()
{
	local target="$1"

	find "${target}" -name "*.ipp" || die
}

transpose()
{
	local target="$1"; shift
	local ipps=( "$@" )

	local -a ret

	for f in "${ipps[@]}"; do
		local header
		local ipp

		header="$(realpath --relative-to "${target}" "${f}")" || die
		ipp="$(realpath "${f%.ipp}.hpp")" || die

		ret+=( "${header}" "${ipp}" )
	done

	OLDIFS="${IFS}"
	IFS=$'\n'
	echo "${ret[*]}"
	IFS="${OLDIFS}"
}

###########
# ACTIONS #
###########

generate()
{
	local target="$1"

	readarray -t ipps < <(get_files "${target}") || die
	[[ "${#ipps[@]}" -eq 0 ]] && return
	readarray -t files < <(transpose "${target}" "${ipps[@]}") || die

	set -- "${files[@]}"

	while [[ "$#" -ne 0 ]]; do
		cat << EOF
If:
  PathMatch: $1
CompileFlags:
  Add: [-include, "$2"]
EOF

		shift 2
		[[ "$#" -eq 0 ]] || echo
	done
}

usage()
{
	cat << EOF
usage:
  ${NAME} -h
  ${NAME} [target directory]

The aim of this script is to generate a minimal clangd configuration (.clangd in
the project root) enabling the LSP to process .ipp files correctly. Therefore,
the basic use of this script is to redirect its output to .clangd.

options:
  -h, --help    Print this message

${NAME} Copyright (C) 2025 Mattéo Rossillol‑‑Laruelle <beatussum@protonmail.com>
This program comes with ABSOLUTELY NO WARRANTY; for details type \`show w'.
This is free software, and you are welcome to redistribute it
under certain conditions; type \`show c' for details.
EOF
}

########
# MAIN #
########

main()
{
	local target

	while [[ "$#" -ne 0 ]]; do
		case "$1" in
			-h|--help)
				usage
				exit 0

				;;

			-*)
				usage
				die "\`$1\` is not recognized"

				;;

			--)
				target="$2"
				break

				;;

			*)
				target="$1"
				;;
		esac

		shift
	done

	[[ -n "${target}" ]] || target="${PWD}"

	generate "${target}" || die
}

main "$@"
